server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kimjongha99/Spring-Cloud-Config
          username: ENC(Wth2cpf4K6WnZgZNmjQ2ROuyEEQbuRIx)
          password: ENC(Z5UfB0DVRuq+5q2KhuSUp4v0e2e2rGPA)
