server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/kims/Documents/GitHub/SpringCloudGateway/eureka/git-local-repo/ecommerce.yml

