server:
  port: 0


spring:
  application:
    name: discovery-client

eureka:
  client:
    register-with-eureka: true #???? ????
    fetch-registry: true # ?????
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # 0???(????)? ?????? ??????? ??? ????? Eureka??? 1?? ???? ??? ????. ?? ???? ?? ???? ?????.

