
server:
  port: 8761
spring:
  application:
    name: eureka
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8080/}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
