server:
  port: 8080


spring:
  application:
    name: apigateway-server


  eureka:
    client:
      register-with-eureka: true #유레카에 서버등록
      fetch-registry: true # 지속적감지

  service-url:
    defaultZone: http://localhost:8761/eureka